package FindBook::Model::FindBookDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'FindBook::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:findbook',
        user => 'findbook',
        password => '58862455',
        AutoCommit => q{1},
    }
);

=head1 NAME

FindBook::Model::FindBookDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<FindBook>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<FindBook::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.59

=head1 AUTHOR

Zhongqiang Shen

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
